services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-app:
    depends_on:
      - mysqldb
    build: ../demo
    container_name: spring-app
    env_file: ./.env
    ports:
      - $SPRING_APP_PORT:$SPRING_APP_PORT
    volumes:
      - .m2:/root/.m2

volumes:
  db:
