CREATE SCHEMA IF NOT EXISTS demo;
USE demo;

CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    gender ENUM('MALE', 'FEMALE', 'ATTACK_HELICOPTER', 'OTHER') NOT NULL,
    email VARCHAR(255)
);